apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: app-yaml
spec:
  compositeTypeRef:
    apiVersion: nest.crossplane.io/v1
    kind: App
  mode: Pipeline
  pipeline:
  - step: create-deployment-and-service
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: deployment
        base:
          apiVersion: apps/v1
          kind: Deployment
          spec:
            template:
              metadata:
                annotations:
                  nest.crossplane.io/enforce: "hpa-requests-v1"
              spec:
                containers:
                - name: app
                  resources:
                    requests:
                      cpu: "100m"
                      memory: "128Mi"
                    limits:
                      cpu: "500m"
                      memory: "256Mi"
                  ports:
                  - containerPort: 80
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.labels[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.selector.matchLabels[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.template.metadata.labels[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.image
          toFieldPath: spec.template.spec.containers[0].image
        - type: FromCompositeFieldPath
          fromFieldPath: spec.port
          toFieldPath: spec.template.spec.containers[0].ports[0].containerPort
        - type: ToCompositeFieldPath
          fromFieldPath: status.availableReplicas
          toFieldPath: status.replicas
        readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Available
            status: "True"
      - name: service
        base:
          apiVersion: v1
          kind: Service
          spec:
            ports:
            - protocol: TCP
              port: 8080
              targetPort: 80
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.labels[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.selector[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.port
          toFieldPath: spec.ports[0].port
        - type: ToCompositeFieldPath
          fromFieldPath: spec.clusterIP
          toFieldPath: status.address
        readinessChecks:
        - type: NonEmpty
          fieldPath: spec.clusterIP
      - name: hpa
        base:
          apiVersion: autoscaling/v2
          kind: HorizontalPodAutoscaler
          spec:
            minReplicas: 1
            maxReplicas: 3
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: app
            metrics:
            - type: Resource
              resource:
                name: cpu
                target:
                  type: Utilization
                  averageUtilization: 70
            - type: Resource
              resource:
                name: memory
                target:
                  type: Utilization
                  averageUtilization: 70
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.labels[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.scaleTargetRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.minReplicas
          toFieldPath: spec.minReplicas
        - type: FromCompositeFieldPath
          fromFieldPath: spec.maxReplicas
          toFieldPath: spec.maxReplicas
        - type: FromCompositeFieldPath
          fromFieldPath: spec.utilization
          toFieldPath: spec.metrics[0].resource.target.averageUtilization
        - type: FromCompositeFieldPath
          fromFieldPath: spec.utilization
          toFieldPath: spec.metrics[1].resource.target.averageUtilization
        readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: ScalingActive
            status: "True"
        - type: MatchCondition
          matchCondition:
            type: AbleToScale
            status: "True"
      - name: ingress
        base:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
              cert-manager.io/cluster-issuer: letsencrypt-development
          spec:
            ingressClassName: nginx
            rules:
            - http:
                paths:
                - path: "/"
                  pathType: Prefix
                  backend:
                    service:
                      name: app
                      port:
                        number: 80
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.labels[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.ingressClassName
          toFieldPath: spec.ingressClassName
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.rules[0].http.paths[0].backend.service.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.port
          toFieldPath: spec.rules[0].http.paths[0].backend.service.port.number
        # Default TLS secret name derived from app name, overridable by spec.tlsSecretName
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.tls[0].secretName
          transforms:
          - type: string
            fmt: "%s-tls"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.host
          toFieldPath: spec.rules[0].host
        - type: FromCompositeFieldPath
          fromFieldPath: spec.host
          toFieldPath: spec.tls[0].hosts[0]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.tlsSecretName
          toFieldPath: spec.tls[0].secretName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.clusterIssuer
          toFieldPath: metadata.annotations[cert-manager.io/cluster-issuer]
