apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: apps.nest.crossplane.io
spec:
  scope: Namespaced
  group: nest.crossplane.io
  names:
    kind: App
    plural: apps
  defaultCompositionUpdatePolicy: Manual
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
     openAPIV3Schema:
       type: object
       properties:
        spec:
          type: object
          properties:
            compositionSelector:
              description: Select a Composition by matching its labels.
              type: object
              properties:
                matchLabels:
                  type: object
                  additionalProperties:
                    type: string
            image:
              description: The app's OCI container image.
              type: string
            port:
              description: The port the app listens on.
              type: integer
            minReplicas:
              description: Minimum number of replicas for HPA.
              type: integer
              minimum: 1
            maxReplicas:
              description: Maximum number of replicas for HPA.
              type: integer
              minimum: 1
            utilization:
              description: Target average utilization percentage used for both CPU and memory metrics.
              type: integer
              minimum: 1
              maximum: 100
            host:
              description: Optional hostname for Ingress routing.
              type: string
            clusterIssuer:
              description: cert-manager ClusterIssuer name to use for certificate issuance.
              type: string
              default: letsencrypt-development
            ingressClassName:
              description: Optional Ingress class name (e.g., nginx).
              type: string
              default: nginx
          required:
          - image
          - port
          - minReplicas
          - maxReplicas
          - utilization
        status:
          type: object
          properties:
            replicas:
              description: The number of available app replicas.
              type: integer
            address:
              description: The app's IP address.
              type: string