apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: default
  labels:
    ingress: "false"
spec:
  compositeTypeRef:
    apiVersion: nest.crossplane.io/v1
    kind: App
  mode: Pipeline
  pipeline:
  - step: create-deployment-service-hpa
    functionRef:
      name: crossplane-contrib-function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: secret
        base:
          apiVersion: v1
          kind: Secret
          type: Opaque
          data: {}
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
          transforms:
          - type: string
            string:
              type: Format
              fmt: "%s-env"
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.labels[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.envFile
          toFieldPath: data[".env"]
          policy:
            fromFieldPath: Optional
        readinessChecks:
        - type: None
      - name: deployment
        base:
          apiVersion: apps/v1
          kind: Deployment
          spec:
            template:
              metadata:
                annotations:
                  nest.crossplane.io/enforce: "hpa-requests-v1"
              spec:
                containers:
                - name: app
                  resources:
                    requests:
                      cpu: "100m"
                      memory: "128Mi"
                    limits:
                      cpu: "500m"
                      memory: "256Mi"
                  ports:
                  - containerPort: 80
                  volumeMounts:
                  - name: env-volume
                    mountPath: /app/.env
                    subPath: .env
                volumes:
                - name: env-volume
                  secret:
                    secretName: app-env
                    optional: true
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.labels[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.selector.matchLabels[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.template.metadata.labels[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.image
          toFieldPath: spec.template.spec.containers[0].image
        - type: FromCompositeFieldPath
          fromFieldPath: spec.command
          toFieldPath: spec.template.spec.containers[0].command
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.args
          toFieldPath: spec.template.spec.containers[0].args
          policy:
            fromFieldPath: Optional
        - type: FromCompositeFieldPath
          fromFieldPath: spec.port
          toFieldPath: spec.template.spec.containers[0].ports[0].containerPort
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.template.spec.volumes[0].secret.secretName
          transforms:
          - type: string
            string:
              type: Format
              fmt: "%s-env"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.envFile
          toFieldPath: spec.template.metadata.annotations[nest.crossplane.io/env-checksum]
          policy:
            fromFieldPath: Optional
        readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: Available
            status: "True"
      - name: hpa
        base:
          apiVersion: autoscaling/v2
          kind: HorizontalPodAutoscaler
          spec:
            minReplicas: 1
            maxReplicas: 3
            scaleTargetRef:
              apiVersion: apps/v1
              kind: Deployment
              name: app
            metrics:
            - type: Resource
              resource:
                name: cpu
                target:
                  type: Utilization
                  averageUtilization: 70
            - type: Resource
              resource:
                name: memory
                target:
                  type: Utilization
                  averageUtilization: 70
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.labels[nest.crossplane.io/app]
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.scaleTargetRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.minReplicas
          toFieldPath: spec.minReplicas
        - type: FromCompositeFieldPath
          fromFieldPath: spec.maxReplicas
          toFieldPath: spec.maxReplicas
        - type: FromCompositeFieldPath
          fromFieldPath: spec.utilization
          toFieldPath: spec.metrics[0].resource.target.averageUtilization
        - type: FromCompositeFieldPath
          fromFieldPath: spec.utilization
          toFieldPath: spec.metrics[1].resource.target.averageUtilization
        readinessChecks:
        - type: MatchCondition
          matchCondition:
            type: ScalingActive
            status: "True"
        - type: MatchCondition
          matchCondition:
            type: AbleToScale
            status: "True"