apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-k8s-admin
rules:
 - apiGroups: ["*"]
   resources: ["*"]
   verbs: ["*"]
 - nonResourceURLs: ["*"]
   verbs: ["*"]
